141 update failure notification
intuit/Trapheus pull request #144
Opened 2023-10-01 01:33 UTC by WallysFerreira

### Description

Change result message of email and slack notification in errors

- Relevant Issues : #141 
- Type of change :
  - [ ] New feature
  - [ ] Bug fix for existing feature
  - [x] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

2023-10-01 01:34 UTC, WallysFerreira commented
Should I add constants with new key strings?

2023-10-01 05:46 UTC, namitad commented
@WallysFerreira yes - lets move them to constants

2023-10-01 05:48 UTC, namitad commented on src/emailalert/email_function.py
> +        result['cause of failure'] = event['status']
lets use constants for these

2023-10-01 05:50 UTC, namitad commented on src/emailalert/email_function.py
> +        result['database id'] = event['DatabaseID']
the event will contain `identifier` for database id and snapshot id is inferred from the database id. sharing a code reference https://github.com/intuit/Trapheus/blob/master/src/snapshot/snapshot_function.py#L11 

lets use the same here

2023-10-01 05:51 UTC, namitad commented on src/emailalert/email_function.py
> +        result['failed step'] = event['taskname'] + 'Error'
this should be `result['failed step'] = event['taskname'] `

2023-10-01 05:52 UTC, namitad commented on src/emailalert/email_function.py
> +        result['failed step'] = event['Error']
similar to above: `result['failed step'] = event['taskname']`

2023-10-01 05:55 UTC, namitad commented on src/emailalert/email_function.py
> +    <p>""" + result['failed step'] + """ : """ + result['cause of failure'] + """</p>
this message should be updated to contain the message in the new format.

2023-10-01 05:56 UTC, namitad requested changes
have added some comments. please address

2023-10-01 05:56 UTC, namitad commented
@WallysFerreira as part of the PR description, could you also add a screenshot of the new email and slack notification post your changes?

2023-10-01 20:07 UTC, WallysFerreira commented
> @WallysFerreira as part of the PR description, could you also add a screenshot of the new email and slack notification post your changes?

Yes I can do that

2023-10-03 04:16 UTC, namitad commented on src/emailalert/email_function.py
> +        result['failed step'] = event['taskname']
can we move all these keys to constants?

2023-10-03 04:18 UTC, namitad commented on src/emailalert/email_function.py
> +        result['database id'] = event['Identifier']
can we move the initialisation of `result['database id']` and `result['snapshot id']` outside of the if else loop as these will be common

2023-10-03 04:19 UTC, namitad commented on src/slackNotification/slack_notification.py
> +        message['snapshot id'] = event['snapshotid']
1. can we move the initialisation of `result['database id']` and `result['snapshot id']` outside of the if else loop as these will be common. 

2. here too - the snapshot id will be of the format `event['Identifier'] + constants.SNAPSHOT_POSTFIX`

2023-10-03 04:26 UTC, namitad commented
@WallysFerreira could you check why the PR build on circleci is failing?

2023-10-03 12:01 UTC, WallysFerreira commented
> @WallysFerreira could you check why the PR build on circleci is failing?

Yeah I will do that

2023-10-03 12:38 UTC, WallysFerreira commented
circleci check is now passing, apparently there was an unit test failing and I think that was causing the check to fail too.

I'll add the screenshots you asked for soon

2023-10-04 04:46 UTC, namitad commented on src/emailalert/email_function.py
> +    <p>database id:""" + result['database id'] + """</p>
can we use the constants here as well?

2023-10-04 04:47 UTC, namitad commented
@WallysFerreira some minor comments. once you share the screenshots of the final email/slack, i will go ahead and approve the PR

2023-10-04 22:41 UTC, WallysFerreira commented
I'm having some issues running the application on my computer to take the screenshots

2023-10-05 04:07 UTC, namitad commented
@WallysFerreira could you elaborate - what issues are you facing?

2023-10-05 10:37 UTC, WallysFerreira commented
Maybe I jumped some step on the tutorial, but when it tries to deploy to AWS it returns

Error: Template file not found at /home/wf/Trapheus/deploy.yaml

2023-10-05 13:18 UTC, namitad commented
@WallysFerreira do reverify your setup and a give it a try again. If it doesnt work, let me know - i can try running your changes locally to verify the output.

2023-10-05 14:09 UTC, WallysFerreira commented
I've tried running on a codespace and it's still returning an error, even though there is a template.yaml and deploy.yaml on the directory.
If you could run the changes locally I'd really appreciate it 

FileNotFoundError: [Errno 2] No such file or directory: 'sam package --template-file template.yaml --output-template-file deploy.yaml --s3-bucket teste-741284363623 --region us-east-2'

2023-10-05 17:33 UTC, namitad commented
Ok.. give me a day or two. Will try this locally and get back to you.

2023-10-08 14:18 UTC, namitad commented
@WallysFerreira i ran your changes locally. but i get the following error: 
```
{
  "errorMessage": "'Identifier'",
  "errorType": "KeyError",
  "requestId": "9c87e534-7933-4044-9295-d8a6834c23c8",
  "stackTrace": [
    "  File \"/var/task/email_function.py\", line 18, in lambda_handler\n    result[constants.DB_ID] = event['Identifier']\n"
  ]
}
```
<img width="1395" alt="Screenshot 2023-10-08 at 7 46 49 PM" src="https://github.com/intuit/Trapheus/assets/23234773/ae0ce27b-a634-4d6f-b8af-1a28a7473ba8">

can we check why `identifier` is not part of the input and if any changes need to be made in the template.yaml to cascade this input?

2023-10-09 14:13 UTC, WallysFerreira commented
Yeah sure I'll look into it and use the new install.py. Thanks

2023-10-09 16:27 UTC, namitad commented
@WallysFerreira i have merged the fix for install.py. can you pull the latest on your branch and try - no need to use a separate version of the file

2023-10-10 22:40 UTC, WallysFerreira commented
I think the error was caused by the capital 'i' in identifier, but can't actually check because I'm getting another error when running install.py

Error: Unable to upload artifact src/common/common.zip referenced by ContentUri parameter of CommonLambdaLayer resource.
Unable to locate credentials

2023-10-11 06:09 UTC, namitad commented
@WallysFerreira looks like your temporary aws credentials may have expired. could you refresh and try again?

2023-10-14 22:13 UTC, WallysFerreira commented
I tried with new aws credentials and still got the same error :(
Could you please try running it locally?

2023-10-15 10:03 UTC, stationeros commented
@namitad / @WallysFerreira there is a couple of issues in the way this is implemented. The way we are getting the identifier is a bit off. The event that gets generated is  this

```
{'Error': 'SnapshotCreationException', 'Cause': '{"errorMessage": "Identifier:database-3 \\nAn error occurred (DBClusterNotFoundFault) when calling the CreateDBClusterSnapshot operation: DBCluster not found: database-3", "errorType": "SnapshotCreationException", "requestId": "6568ebed-be45-4962-bdc3-35bf080c4322", "stackTrace": ["  File \\"/var/task/cluster_snapshot_function.py\\", line 25, in lambda_create_cluster_snapshot\\n    util.eval_snapshot_exception(error, cluster_id, rds)\\n", "  File \\"/opt/python/utility.py\\", line 72, in eval_snapshot_exception\\n    raise custom_exceptions.SnapshotCreationException(error_message)\\n"]}'} | event is {'Error': 'SnapshotCreationException', 'Cause': '{"errorMessage": "Identifier:database-3 \\nAn error occurred (DBClusterNotFoundFault) when calling the CreateDBClusterSnapshot operation: DBCluster not found: database-3", "errorType": "SnapshotCreationException", "requestId": "6568ebed-be45-4962-bdc3-35bf080c4322", "stackTrace": [" File \\"/var/task/cluster_snapshot_function.py\\", line 25, in lambda_create_cluster_snapshot\\n util.eval_snapshot_exception(error, cluster_id, rds)\\n", " File \\"/opt/python/utility.py\\", line 72, in eval_snapshot_exception\\n raise custom_exceptions.SnapshotCreationException(error_message)\\n"]}'}
```

As you can see there is no direct way of getting the Identifier as a key. We have a utilty function defined that needs to be utilised https://github.com/intuit/Trapheus/blob/master/src/common/python/utility.py#L33 to get the identifier from the event.

Secondly, the way ```TASK_NAME``` is getting extracted also is a bit odd. Its not present directly in the event but its in the context object of the lambda runtime. You can simply do context.function_name to get that.

With the above changes, you guys should be able to get that out. Let me know if you need help 

<img width="730" alt="Screenshot 2023-10-15 at 3 32 47 PM" src="https://github.com/intuit/Trapheus/assets/112308320/26d211d8-3aa9-45f6-b1bb-0e02771e004e">

2023-10-17 04:55 UTC, namitad commented
@WallysFerreira it would still run into a similar issue (as mentioned by @stationeros above) with the "identifier" change. we need to explicitly pass the identifier name to the state where alerts are being sent. Can we look at using a pass state https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-pass-state.html to add this?

This can also be used in the future if we need to add additional values - such as execution id.

2023-10-17 04:59 UTC, namitad commented
@stationeros yes - taskname is being cascaded because in the context object - it would either be the email alert/slack notification lambda name. even if set from each step, it would expose the lambda function name to the user instead of the flow. we can revisit if this change needs to be done and maybe address that as a separate issue.

2023-10-17 08:46 UTC, stationeros commented
I am fine with whatever you guys choose to decide on this. Also I feel along with the documentation , it would be helpful to point to the code as to how we are passing that state today via template.yaml for better understanding.

2023-10-17 11:53 UTC, WallysFerreira commented
@stationeros that's super helpful, thanks. I'll make those changes asap.

@namitad I'll try to look into using a pass state afterwards, but it would still work without it if I make the changes @stationeros said, right? Just so I can do one thing at a time

2023-10-17 11:58 UTC, stationeros commented
@WallysFerreira Thats right? You can possibly fix the instance identifier and the task name chaining can be done later. I can break this into subtasks for this to be managed better

2023-10-28 03:18 UTC, stationeros commented
@WallysFerreira  Can you make the code change for instance identifier , you just need to call this inside the lambda , we can then merge this commit

2023-11-08 14:42 UTC, stationeros commented
@WallysFerreira  Closing this PR due to inactivity, feel free to re-open and submit if you are still working on this.

2023-11-08 14:42 UTC, closed without merging