Add Spanish translations of docs
intuit/Trapheus pull request #158
Opened 2023-10-04 08:15 UTC by virejdasani

### Description

Thanks for contributing this Pull Request. Make sure that you submit this Pull Request against the `master` branch of this repository, add a brief description, and tag the relevant issue(s) and PR(s) below.

Translated the docs to spanish.

- Relevant Issues : #157 
- Relevant PRs : (optional)
- Type of change :
  - [ ] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [x] Addition or Improvement of documentation

2023-10-05 04:05 UTC, namitad commented on README.md
> +- **Important:** this application uses various AWS services and there are costs associated with these services after the Free Tier usage - please see the [AWS pricing page](https://aws.amazon.com/pri
can we remove all the unrelated changes from this file. @virejdasani your required changes seem to be in this line https://github.com/intuit/Trapheus/pull/158/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17 , would my understanding be correct?

2023-10-05 04:05 UTC, namitad commented on docs/README.es.md
> +5. Una o más instancias de una base de datos RDS que desea restaurar.
the translated file seems incomplete. could you check?

2023-10-08 12:03 UTC, namitad requested changes
@virejdasani please address the comments

2023-10-17 13:27 UTC, stationeros commented
@virejdasani I am going to cut a release this week , do let us know if you can address the comments by then

2023-11-06 04:39 UTC, stationeros commented
Closing this owing no response for a month

2023-11-06 04:39 UTC, closed without merging