Issue-8: Added changes to accept an optional snapshot id for DB instance
intuit/Trapheus pull request #38
Opened 2020-10-02 06:30 UTC by mamata49

### Description

Thanks for contributing this Pull Request. Make sure that you submit this Pull Request against the `master` branch of this repository, add a brief description, and tag the relevant issue(s) and PR(s) below.

- Relevant Issues : https://github.com/intuit/Trapheus/issues/8
- Relevant PRs : (optional)
- Type of change :
  - [Y ] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

Added optional snapshot_id param to DB instance codepath. Have made the parameter optional to keep it backwards compatible.

2020-11-25 18:29 UTC, namitad commented on src/common/python/utility.py
>  def get_modified_identifier(identifier):
since a new method `get_modified_response` has been added, can this one be removed?

2020-11-25 18:30 UTC, namitad commented on src/common/python/utility.py
>      db_snapshot_id = db_instance_id + constants.SNAPSHOT_POSTFIX
this may no longer be valid with your change

2020-11-25 18:30 UTC, namitad commented on src/common/python/utility.py
> +    response["snapshot_id"] = get_modified_value(get_snapshot_id(event))
snapshot identifiers do not need the `-temp` check

2020-11-25 18:40 UTC, namitad commented on src/common/python/utility.py
> +    snapshot_id = event['snapshot_id']
can remove the variable assignment and directly return event['snapshot_id']

2020-11-25 18:54 UTC, namitad requested changes
@mamata49 could you add the changes for the cluster based dbs as well.. presently your changes are only for the single instance type and not the aurora cluster based ones

2021-05-10 16:09 UTC, stationeros commented
@mamata49  I am closing this as the PR has been in a dormant state for too long. Do re-open if you feel differently.

2021-05-10 16:09 UTC, closed without merging